### ISSUE TITLE
Update Domainlist

### ISSUE THREAD

**Issue by rowbean** [robbi5/german-gov-domains#10]
Hi,
just found some domains which are redirected to a new ssl-secured url.
illingen-saar.de -> illingen.de
perl-mosel.de ->perl.saarland
sanktingbert.de ->st-ingbert.de

**Comment by robbi5** [comment]
Hey, thanks for finding this changes :)

The best way to update this would be to update the Wikipedia Pages of the Cities in the German Wikipedia (de.wikipedia.org - for humans) and in Wikidata (wikidata.org - for machines, and projects like this)

Example: The Domain of Illingen (Saar) was already updated in https://de.wikipedia.org/wiki/Illingen_(Saar) - but not yet in https://www.wikidata.org/wiki/Q517653

**Comment by rowbean** [comment]
Thanks for the explanation :)
Fixed it.
